version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: ~/leet
    steps:
      - checkout
      - restore_cache:
          key: v2
      - run: |
          pip install virtualenv
          virtualenv ~/venv
          . ~/venv/bin/activate
          make install
      - run: |
          . ~/venv/bin/activate
          make ci
      - save_cache:
          key: v2
          paths:
            - "~/.cache/pip"
            - "~/venv"
      - store_test_results:
          path: junit.xml
